name: Fire dispatch # test

on:
  push:
    branches:
      # - master
      - none

jobs:
  fire-dispatch-event:
    name: Fire dispatch event
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        uses: octokit/request-action@v2.x
        with:
          # https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
          route: POST /repos/{repo}/dispatches
          repo: ${{ github.repository }}
          event_type: 'test_result'
          client_payload: |
            {
              "passed": false,
              "message": "Error: timeout"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN_GH }}
